FROM ghcr.io/prefix-dev/pixi:latest
LABEL org.opencontainers.image.source=https://github.com/samwitham/ismb2025
LABEL org.opencontainers.image.title=single_cell_perturbation_modelling
LABEL org.opencontainers.image.version=0.1
LABEL org.opencontainers.image.description="This is an image for running single cell perturbation modelling"

ARG PYTHON_VERSION=3.8

RUN mkdir /project

# Create a unified pyproject.toml for all dependencies with CUDA 11.6 and Python 3.8
RUN cat <<EOF > /project/pyproject.toml
[project]
name = "single_cell_perturbation_modelling"
version = "0.1.0"
description = "Unified environment for scgen and scpram"
authors = [
    {name = "samwitham"},
]
requires-python = "==$PYTHON_VERSION.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
scanpy = "==1.9.3"
scvi-tools = "*"
optuna = "*"
ipywidgets = "*"

[tool.pixi.pypi-dependencies]
scpram = "*"
scgen = "*"
pertpy = "*"
torch = "==1.3.1"

[tool.pixi.system-requirements]
cuda = "11.6"

[tool.pixi.tasks]
install-kernel = "python -m ipykernel install --user --name pixi-env --display-name 'Pixi Env'"
install-rkernel = "R -e 'IRkernel::installspec()'"
install-all = { depends-on =[
    "install-kernel",
    "install-rkernel"
], cmd = "echo 'All packages installed successfully'"}
EOF

WORKDIR /project

RUN apt-get update && apt-get install -y procps apt-utils libgsl-dev locales libicu-dev libcurl4-openssl-dev \
    libnode-dev \
    libxml2-dev \
    make \
    pandoc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8 

# Install all dependencies in the default environment
RUN pixi install --manifest-path pyproject.toml

RUN pixi add r-devtools r-biocmanager r-remotes r-base r-roxygen2 r-testthat r-usethis r-argparser r-ggplot2 r-data.table r-svglite r-rcpp r-future bioconductor-edger r-dplyr r-matrix r-purrr r-box r-seurat r-bit64 r-openxlsx r-ape r-pheatmap r-ggpubr r-qs r-markdown r-ggnewscale r-emmeans r-multcomp r-readxl r-progress r-ggalt r-ggprism r-hdf5r r-pak

# Run setup tasks
RUN pixi run install-all

# Place executables in the environment at the front of the path
ENV PATH="/project/.pixi/envs/default/bin:$PATH"

# ARG GITHUB_PAT
# ENV GITHUB_PAT=$GITHUB_PAT